#!/usr/bin/perl
# Will try to load all needed perl modules, fails if any not available
use Data::Dumper;
use strict;
use DBI;
use POSIX;
use IO::Socket::INET;
use Encode;
use Gtk2;
use Gtk2::GladeXML;
use Gtk2::Pango;
use Gtk2::Spell;
use Gtk2::TrayIcon;
use Gnome2::Canvas;
use Getopt::Std;
use Glib;

my $prefix="";
my $install_db = 1;
my $install_files = 1;
my $dbpass = "";
my $dbuser = "root";
my $adminuser = "";
my %opts;

getopts('f:du:p:a:h', \%opts);
if (defined $opts{h}) {
	print "Usage: install [-h] [-f PREFIX] [-d] [-u DBUSER] [-p DBPASS] [-a ADMINUSER]\n";
	exit(1);
}
if (defined $opts{f}) {
	$prefix=$opts{f};
	$install_db = 0;
}
if (defined $opts{a}) {
	$adminuser = $opts{a};
}
if (defined $opts{d}) {
	$install_files = 0;
}
if (defined $opts{u}) {
	$dbuser = $opts{u};
}
if (defined $opts{p}) {
	$dbpass = $opts{p};
}


print "Lyric Display System\n";
print "--------------------\n";
print "This script will check that the nessecary items are installed\n";
print "then install the files and create the MySql tables nessecary\n";

my $bindir   = $prefix."/usr/bin/";
my $etcdir   = $prefix."/etc/lyricue/";
my $sharedir = $prefix."/usr/share/lyricue/";
my $ldssharedir = $prefix."/usr/share/lds/";
my $ldsetcdir = $prefix."/etc/lds/";
my $docdir = $prefix."/usr/share/doc/lyricue/";
my $localedir = $prefix."/usr/share/locale/";
my @parentdirs = ($prefix."/etc",$prefix."/usr", $prefix."/usr/share", $prefix."/usr/share/doc", $prefix."/usr/share/locale");

my %replace = ( $sharedir."lyricue.png" => 0644,
		$sharedir."lyricue-icon.png" => 0644,
		$sharedir."lyricue.glade" => 0644,
		$bindir."lyricue" => 0644,
		$bindir."lyricue_remote" => 0644,
		$bindir."lyricue_server" =>0644);

my %addonly = (	$etcdir."access.conf" => 0644,
		$etcdir."default.conf" => 0644
		);

if ($ARGV[0] eq "-u") {
	print "Uninstalling Lyricue\n";
	print "--------------------\n\n";
	print "Do you want to remove global images/backgrounds? (y/N):";
	my $globals = <STDIN>;
	chomp ($globals);
	print "\nDo you want to remove the databases? (y/N):";
	my $database = <STDIN>;
	chomp($database);
	if (uc($database) eq "Y") {
		if ($dbpass eq "") {
			print "Please enter the password for your ".$dbuser." mysql user: ";
			$dbpass=<STDIN>;
			chomp $dbpass;
		}
	}
	print "\n\nAbout to delete Lyricue\n";
	print "\nAre you SURE? (y/N):";
	my $confirm = <STDIN>;
	chomp ($confirm);
	if (uc($confirm) ne "Y") {
		print "\n\nCancelled ... Exiting\n";
		exit;
	}
	print "Removing executables\n";
	system ("rm $bindir/lyricue $bindir/lyricue_server $bindir/lyricue_remote");
	print "Removing most files in share directory\n";
	system ("rm $sharedir/*");
	print "Removing Documentation\n";
	system ("rm -rf $docdir");
	print "Removing System Settings\n";
	system ("rm -rf $etcdir");
	if (uc($globals) eq "Y") {
		print "Removing entire lyricue share directory\n";
		system("rm -rf $sharedir");
	}
	if (uc($database) eq "Y") {
		print "Removing Databases\n";
		system ("echo 'DROP DATABASE lyricDb' | mysql -u $dbuser --password=$dbpass");
		system("echo 'DROP DATABASE bibleDb' | mysql -u $dbuser --password=$dbpass");
		system("echo 'DROP DATABASE mediaDb' | mysql -u $dbuser --password=$dbpass");
		print "Removing Lyric user from the database\n";
		system ("echo \"DELETE FROM user WHERE User='lyric';\"| mysql -u$dbuser --password=$dbpass mysql");

		system("mysqladmin -u$dbuser --password=$dbpass reload");
	}
	print "\n\nUninstalled\n";
} else {
	if ( -d $ldssharedir ) {
		system("mv $ldssharedir $sharedir");
		system("ln -s $sharedir $ldssharedir");
	}
	if ( -d $ldsetcdir ) {
		system("mv $ldsetcdir $etcdir");
		system("ln -s $etcdir $ldsetcdir");
	}

	if ($install_files) {
		print "Creating directories:\n";
		foreach my $dir (@parentdirs, $bindir,$etcdir,$sharedir,$docdir) {
			print "dir -> ".$dir."\n";
			mkdir $dir,0755;
		}
	
		print "\nCopying files:\n";
		foreach my $file (keys %replace) {
			print "file -> ".$file."\n";
			my $basename = $file;
			$basename =~ s/^.*\///g;
			system ("cp ".$basename." ".$file);
		}
	
		foreach my $file (keys %addonly) {
			if ( ! -e $file ) {
				print "file -> ".$file."\n";
				my $basename = $file;
				$basename =~ s/^.*\///g;
				system ("cp ".$basename." ".$file);
			}
		}
		
		my @docs;
		opendir (DIR, "docs" );
		@docs = readdir(DIR);
		closedir (DIR);
		foreach (@docs) {
			if (! /^\./ ) {
				print "doc -> ".$_."\n";
				system ("cp docs/".$_." ".$docdir);
			}
		}
		
		my @locales;
		opendir (DIR, "po");
		@locales = readdir(DIR);
		closedir (DIR);
		foreach (@locales) {
	    		if (! /^\./ ) {
		    	my $locale=$_;
		    	$locale =~ s/\.mo$//g;
		    	my $locdir = $localedir.$locale."/LC_MESSAGES";
		    	mkdir $localedir.$locale;
		    	mkdir $locdir;
		    	print "translation -> ".$locdir."\n";
		    	system ("cp po/".$locale.".mo ".$locdir."/lyricue.mo");
			}
		}
	}
	if ($install_db) {
		my @ary = DBI->available_drivers(1);
		my $mysql = 0;
		foreach ( @ary ) {
	 		if ($_ eq "mysql") {
	 			$mysql = 1;
			}
		}
		if (! $mysql ) {
			die ("The Perl module DBI::mysql is not installed, please install");
		}
	
		if (@ary == 0 ) {
			die "Mysql doesn't appear to be running, please restart it\n";
		}
		if ( $dbpass eq "") {
			print "Please enter the password for your $dbuser mysql user: ";
			my $dbpass=<STDIN>;
			chomp $dbpass;
		}
		
		my $dbh = DBI->connect("DBI:mysql:mysql:localhost", "$dbuser","$dbpass");
		my $sth = $dbh->prepare ("select * from user where User='lyric'");
		my $rv = $sth->execute;
		if ($sth->rows) {
			print "User already setup\n";
		} else {
			print "Creating mysql user..";
			$sth = $dbh->prepare ("insert into user set Host='%',User='lyric',Password='',Select_priv='Y',Insert_priv='Y', Update_priv='Y',Delete_priv='Y'");
			$sth->execute;
			$sth = $dbh->prepare ("insert into user set Host='localhost',User='lyric',Password='',Select_priv='Y',Insert_priv='Y', Update_priv='Y',Delete_priv='Y'");
			$sth->execute;
			print "Done\n";
		}
	
		print "Checking for existing Databases:\n";
		my @ary = DBI->data_sources("mysql");
		my $lyricdb = 0;
		my $bibledb = 0;
		my $mediadb = 0;
		foreach ( @ary ) {
			if (/lyricDb/) {
				print "Found lyricDb\n";
				$lyricdb = 1;
			} elsif (/bibleDb/) {
				print "Found bibleDb\n";
				$bibledb = 1;
			} elsif (/mediaDb/) {
		    		print "Found mediaDb\n";
				$mediadb = 1;
			}
		}
		
		if (! $lyricdb) {
	    		print "Creating lyricDb\n";
			system ("cat mysql/MySQL_create_Table.sql | mysql -u $dbuser --password=$dbpass");
		} else {
			my $dbh2 = DBI->connect("DBI:mysql:lyricDb", "$dbuser","$dbpass");
			my $tables = $dbh2->selectall_arrayref("show tables");
			my %table;
			foreach (@$tables) {
				%table->{$_->[0]} = 1;
			}
			if (! defined %table->{'associations'}) {
				print "Associations table not found\n";
				print "Upgrading database from < 1.2 to 1.2\n";
				system ("cat mysql/Update_1.2.sql | mysql -u $dbuser --password=$dbpass");
				print "Done\n";
			}
		
			my $fields = $dbh2->selectall_arrayref("describe playlist");
			my %trans;
			foreach (@$fields) {
				%trans->{$_->[0]} = 1;
			}
			if (! defined %trans->{'transition'}) {
				print "Transition field not found\n";
				print "Upgrading database from 1.2 to 1.9\n";
				system ("cat mysql/Update_1.9.sql | mysql -u $dbuser --password=$dbpass");
				print "Done\n";
			}
	
		}
		
		if (! $bibledb) {
	    		print "Creating bibleDb\n";
			system ("cat mysql/MySQL_create_bible_KJV.sql | mysql -u $dbuser --password=$dbpass");
		}
	
		if (! $mediadb) {
	    		print "Creating media database\n";
	    		system ("cat mysql/MySQL_create_media.sql | mysql -u $dbuser --password=$dbpass");
		}
	
		system("mysqladmin -u$dbuser --password=$dbpass reload");
	
		if (! $mediadb) {
			print "Importing existing backgrounds/images\n";
			system ("./import_media img $sharedir/images");
			system ("./import_media bg $sharedir/backgrounds");
			print "Done\n";
		}
	}
	
	if ($install_files) {
		if ($adminuser eq "") {
			print "Please enter the user that you will be administering Lyricue from: ";
			$adminuser=<STDIN>;
			chomp $adminuser;
		}
		open (ACCESS, $etcdir."access.conf");
		open (OUT, ">".$etcdir."access.conf.tmp");
		while (<ACCESS>) {
			if (! /^$adminuser/) {
				print OUT $_;
			}
		}
		print OUT $adminuser." = spade\n";
		close OUT;
		close ACCESS;
		system ("mv ".$etcdir."access.conf.tmp ".$etcdir."access.conf");
		
		print "\n\n";
	}
	print "Finished installing Lyricue\n\n";
	print "Run /usr/bin/lyricue_server on one screen\n";
	print "and load up /usr/bin/lyricue on the other\n";
}
