.TH LYRICUE_SERVER 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
lyricue_server \- The GNU Lyric Display System Server
.SH SYNOPSIS
.B lyricue_server
.RB "<-v> <-m> <-c> <-d>"
.SH "DESCRIPTION"
This application is used to edit/display song lyrics on a second screen/projector for use at singing events such as church services.
It is currently being used at Gosford Baptist Church in Gosford, Australia
.PP
This script creates a fullscreen window that is used to display song lyrics (normally on a second screen, projector or similar) OR a scaled server window that can be used to preview songs a given screen.
.SH OPTIONS
.TP
.B \-v
Get lyricue_server version
.TP
.B \-m
Run in miniserv mode (used for preview window in interface)
.TP
.B \-d
Turn on debugging mode. Prints out debugging information
.SH CONFIGURATION
All configuration is done by editing the configuration section in the program
.SH REQUIRES
Perl 5.6 or later, DBI::MySQL, Gtk2-Perl, MySql database
.\".SH "SEE ALSO"
.\"The programs are documented fully by
.\".IR "The Rise and Fall of a Fooish Bar" ,
.\"available via the Info system.
.SH AUTHOR
Chris Debenham <chris@adebenham.com>
Clint Turner <cnt@clintturner.com>
.SH COPYRIGHT
This program is released under the GPL (http://www.gnu.org/copyleft/gpl.html)
.SH VERSION
Lyricue_server Version 1.9.7
