#!/bin/bash

#Update changelog
#bzr log --gnu > ChangeLog

CHANGELOG=debian/changelog
VERSION=`head -1 ${CHANGELOG} |sed -e 's/^.*(\(.*\)).*$/\1/g'|sed -e 's/^.://g'`
LC_ALL=C;export LC_ALL

CONV="s/##VERSION##/${VERSION}/g"
sed --in-place -e $CONV src/lyricue 
sed --in-place -e $CONV help/lyricue.xml

for DIST in maverick lucid natty oneiric
do echo Building for ${DIST}

if [ "$DIST" != "maverick" ]
then cat ${CHANGELOG} | head -1 | sed -e "s/maverick/$DIST/g" -e "s/)/${DIST})/g"  > debian/changelog-new
echo "" >> debian/changelog-new
echo "  * Build for ${DIST}" >> debian/changelog-new
echo "" >> debian/changelog-new
echo " -- Chris Debenham <chris@adebenham.com> " `date -R` >> debian/changelog-new
echo "" >> debian/changelog-new
cat $CHANGELOG >> debian/changelog-new
mv debian/changelog-new debian/changelog
fi
bzr-buildpackage -S
bzr revert debian/changelog
done

echo Update archive
VER=`echo $VERSION | sed -e 's/-[0-9]//g'`
cp ../lyricue_${VER}.orig.tar.gz /var/www/local/lyricue.org/archive/lyricue_${VER}.tar.gz
pushd /var/www/local/lyricue.org/archive
echo "<html><body><h1>Lyricue source archive</h1><table>" > index.php

echo "<tr><td>Size</td><td>Filename</td></tr>" >> index.php
echo "<tr><td colspan=2><h2>Lyricue Source</h2></td></tr>" >> index.php
for F in `ls -r lyricue*`
do SIZE=`du -k $F | cut -f1`K
echo "<tr><td>${SIZE}</td><td><a href='${F}'>${F}</a></td></tr>" >> index.php
done

echo "<tr><td colspan=2><h2>Precue Source</h2></td></tr>" >> index.php
for F in `ls -r precue*`
do SIZE=`du -k $F | cut -f1`K
echo "<tr><td>${SIZE}</td><td><a href='${F}'>${F}</a></td></tr>" >> index.php
done

echo "<tr><td colspan=2><h2>Others</h2></td></tr>" >> index.php
for F in `ls -r |grep -v "^precue" | grep -v "^lyricue"`
do SIZE=`du -k $F | cut -f1`K
echo "<tr><td>${SIZE}</td><td><a href='${F}'>${F}</a></td></tr>" >> index.php
done

popd

echo Rebuild documentation
cp help/lyricue.xml /var/www/local/lyricue.org/documentation
cd /var/www/local/lyricue.org/documentation
./build_wp.sh
# Put things back to how they were
bzr revert src/lyricue
bzr revert help/lyricue.xml
rm src/lyricue.~*~
rm debian/changelog.~*~

echo dput ppa:chris-debenham/lyricue `ls ../*.changes`

