#!/bin/sh
mkdir dist
rm -rf dist/lyricue*

mkdir dist/lyricue-$1
cp images/black.png import_media install images/lyricue.png images/lyricue-icon.png lyricue.glade lyricue lyricue_server access.conf default.conf dist/lyricue-$1

for F in black white gray red green blue yellow orange;do touch dist/lyricue-$1/$F.bg;done

mkdir dist/lyricue-$1/po
for F in po/*.po;do LANG=`basename $F .po`; msgfmt po/$LANG.po -o dist/lyricue-$1/po/$LANG.mo;done

mkdir dist/lyricue-$1/docs
cp docs/AUTHORS docs/COPYING docs/Development.txt docs/example_song.txt docs/INSTALL docs/NEWS docs/README docs/song_template.txt docs/TODO docs/User_Guide.pdf dist/lyricue-$1/docs

mkdir dist/lyricue-$1/mysql
cp mysql/MySQL_create_bible_KJV.sql mysql/MySQL_create_Table.sql mysql/Update_1.2.sql mysql/Update_1.9.sql mysql/MySQL_create_media.sql dist/lyricue-$1/mysql

cd dist
tar cvfz lyricue-$1.tar.gz lyricue-$1
rm lyricue-$1/mysql/MySQL_create_bible_KJV.sql
tar cvfz lyricue-upgrade-$1.tar.gz lyricue-$1
cd ..
rm -rf dist/lyricue-$1
