#!/bin/bash

# Build for intrepid
cp debian/control-jaunty debian/control
HEADER=`cat debian/changelog-cvs | head -1 | sed -e 's/karmic/intrepid/g' -e 's/)/intrepid)/g'` 
echo $HEADER > debian/changelog
echo "  * Rebuild for intrepid " >> debian/changelog
echo "" >> debian/changelog
echo " -- Chris Debenham <chris@adebenham.com> " `date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog-cvs >> debian/changelog
debuild -S -sa -kB734D1F5

# Build for jaunty
cp debian/control-jaunty debian/control
HEADER=`cat debian/changelog-cvs | head -1 | sed -e 's/karmic/jaunty/g' -e 's/)/jaunty)/g'` 
echo $HEADER > debian/changelog
echo "  * Rebuild for jaunty" >> debian/changelog
echo "" >> debian/changelog
echo " -- Chris Debenham <chris@adebenham.com> " `date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog-cvs >> debian/changelog
debuild -S -sa -kB734D1F5

# Build for karmic
cp debian/control-karmic debian/control
cat debian/changelog-cvs > debian/changelog
debuild -S -sa -kB734D1F5

# Build for Lucid
HEADER=`cat debian/changelog-cvs | head -1 | sed -e 's/karmic/lucid/g' -e 's/)/lucid)/g'` 
echo $HEADER > debian/changelog
echo "  * Rebuild for lucid" >> debian/changelog
echo "" >> debian/changelog
echo " -- Chris Debenham <chris@adebenham.com> " `date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog-cvs >> debian/changelog
debuild -S -sa -kB734D1F5

cp debian/control-jaunty debian/control

(cd ..;dput ppa:chris-debenham/lyricue lyricue-cvs*_source.changes)
